### ISSUE TITLE
missing TTL (Time To Live)

### ISSUE THREAD

**Issue by xlmnxp** [philcockfield/file-system-cache#20]
TTL (Time To Live) is expire time to erase cache files

**Comment by negreanucalin** [comment]
This would be awesome to add (TTL)

**Comment by mardikarifqi** [comment]
(+1)

**Comment by MenschenToaster** [comment]
Please add this

**Comment by jessejamesrich** [comment]
Does cache then just live forever?

**Comment by philcockfield** [comment]
This makes sense, I'll get this implemented into the next update.

**Comment by ping-douglasl** [comment]
I just submitted a PR that addresses this issue.
