### ISSUE TITLE
Feature Request: Allow users to specify their hashing algorithm of choice

### ISSUE THREAD

**Issue by trevor-vaughan** [philcockfield/file-system-cache#23]
Presently, the library uses `md5` as a hard coded value in the [Utils](https://github.com/philcockfield/file-system-cache/blob/main/src/common/Util.ts#L44) library.

I would like to be able to adjust the choice of algorithm to help future-proof use of the library.

**Comment by philcockfield** [comment]
This makes sense, I'll get this implemented into the next update.

**Comment by rmarone** [comment]
Could merge #26 as a stopgap to get off of md5 for now.

**Comment by philcockfield** [comment]
Closed with https://github.com/philcockfield/file-system-cache/pull/26

**Comment by philcockfield** [comment]
https://github.com/philcockfield/file-system-cache/pull/26

**Comment by trevor-vaughan** [comment]
@philcockfield Appreciate the update to `sha1` but could  this be re-opened to keep the request for hash specification alive?

**Comment by philcockfield** [comment]
Good call @trevor-vaughan

**Comment by philcockfield** [comment]
I've been assessing modern, ESM hashing libs recently, so might get this implemented in the next week or so.
