### ISSUE TITLE
v2.4.0 breaks on case-sensitive filesystems (i.e. Linux)

### ISSUE THREAD

**Issue by TooTallNate** [philcockfield/file-system-cache#30]
The PR https://github.com/philcockfield/file-system-cache/pull/29 seems to have broken on case-sensitive filesystems, due to this change in casing in the import call:

<img width="885" alt="Screenshot 2023-06-26 at 4 34 22 PM" src="https://github.com/philcockfield/file-system-cache/assets/71256/b7c4868e-af4f-45de-9095-0486f6e12cf3">

Noticed this by trying to deploy a Storybook application, which has started failing at build-time.

**Comment by TooTallNate** [comment]
I see that the filename was also renamed to be lowercase, so the code itself should be fine. This is probably an issue with your local build which was then published, so I suggest trying to clear out any build artifacts and then trying to build again (and publish a fixed version 😄).

**Comment by zombieJ** [comment]
https://unpkg.com/browse/file-system-cache@2.4.0/lib/common/

npm still keep the upcase:

![截屏2023-06-27 11 34 10](https://github.com/philcockfield/file-system-cache/assets/5378891/a4695ea3-5287-4700-9482-6974fbb59f65)

**Comment by augustobmoura** [comment]
This is a big deal, I can't run storybook cli from npx because it resolves to the latest file-system-cache and that is broken on linux.

Quick reproduction steps:
```bash
docker run -it --rm node:16 npx -y storybook@latest --version
```

It looks like the paths are correct on master, but for some reason the file was capitalized on the computer that made the release. I assume making a new release from a newly cloned repo should fix it.

@philcockfield could you please make a new release?

**Comment by dzek69** [comment]
For anyone looking for a workaround for storybook init:
- install it as a normal dependecy like `pnpm add storybook` - you will need it anyway (update the command for yarn/npm/whatever you use)
- fix the filename somewhere in the node_modules folder (the path depends on package manager, so again - adjust for what you use)
- run `pnpm exec storybook init`
-  🎉

**Comment by joriswitteman** [comment]
FWIW a workaround is present in Storybook 7.0.24, just waiting for the release to [pass their CI/CD](https://github.com/storybookjs/storybook/pull/23185)

**Comment by JReinhold** [comment]
Storybook v7.0.24 has now been released that should workaround this issue for now.

**Comment by trevor-vaughan** [comment]
Confirmed on independent use of the library. Renaming the file from `Util.js` to `util.js` resolves the issue.

**Comment by mike-potter** [comment]
Also just ran into this.  This is super critical.  Rather than patching downstream dependencies can we get a new release of `file-system-cache` that fixes this asap?  Confirmed that renaming the file to `util.js` solves it.

**Comment by mike-potter** [comment]
If it's an npm package issue, maybe going back to the uppercase `Util.js` would be better until a better fix can be found.

**Comment by dep** [comment]
I still get the error with `7.0.24`

@storybook/cli v7.0.24
```
info => Cleaning outputDir: /storybook-static/src
info => Loading presets
ERR! Error: Cannot find module './util'
```

**Comment by mike-potter** [comment]
Storybook 7.0.24 works for me here, but I had to clean my yarn cache, remove my lock file and node_modules folder to get a fresh build of dependencies.

**Comment by mike-potter** [comment]
Do a `yarn list --pattern file-system-cache` to see if you are getting the 2.3.0 version that works.

**Comment by philcockfield** [comment]
ON IT...(WTF!)

**Comment by philcockfield** [comment]
Published patch to NPM →  [2.4.1](https://www.npmjs.com/package/file-system-cache/v/2.4.1)

Sincerest apologies for that SNAFU everyone!

**Comment by philcockfield** [comment]
I'll leave this open for a little while - please sing out if anyone's having further problems related to this.

**Comment by philcockfield** [comment]
Cool, no more comments, so looks like this is sorted. Thanks all.
