### ISSUE TITLE
`@types/ramda` is missing, causing type errors

### ISSUE THREAD

**Issue by JReinhold** [philcockfield/file-system-cache#32]
It appears that `v2.4.1` introduces a type error that is caught in the Storybook CI here, for [a PR that upgrades to said version](https://github.com/storybookjs/storybook/pull/23253): https://app.circleci.com/pipelines/github/storybookjs/storybook/53837/workflows/8ef6bf7f-46c8-4605-8fa2-f804ed46350c/jobs/552019

It looks like you're exporting types from `ramda`, but [`@types/ramda` is only set as a `devDependency`](https://github.com/philcockfield/file-system-cache/blob/main/package.json#L21), so it's not present to users (like us) that depends on your library.

This is what's exported: https://www.npmjs.com/package/file-system-cache?activeTab=code

My suggestion would be to bundle with [`tsup`](https://tsup.egoist.dev/), as that bundles in the types as well. But that might be a bigger task, so moving `@types/ramda` to a `dependency` is also an option.

This problem only occurs if `skipLibCheck` in `tsconfig` is `false`, which is the default.

I'm unsure why this problem was only introduced in `2.4.1`, and not before.

**Comment by philcockfield** [comment]
Hey, thanks @JReinhold.

I've moved `@types/ramda` into the `{ dependencies }`.

Have republished on NPM as [v2.4.2](https://www.npmjs.com/package/file-system-cache/v/2.4.2)
I'll leave this PR open, please sing out if that does or doesn't resolve this.

Thanks!

**Comment by JReinhold** [comment]
Thanks @philcockfield. It seems like the problem has now "moved on" to `@types/fs-extra`, giving the same error.

https://app.circleci.com/pipelines/github/storybookjs/storybook/54659/workflows/b1907d3b-f0c8-4539-9f94-804d56c8e46e/jobs/555993/parallel-runs/0?filterBy=ALL

I don't think any of the other `@types` dependencies need to be moved, as they are test related and probably won't be part of the final bundle anyway.
